# conda env create --file environment.yml
name: {{ cookiecutter.name }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - seaborn
  - pandas
  - numpy
  - matplotlib
  {% if cookiecutter.packages == "All" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - statsmodels
  - scipy
  {% endif -%}
  - pip
  {% if cookiecutter.packages == "All" -%}
  - scikit-learn
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  {% if cookiecutter.packages == "All" -%}
  - pip:
    - pyhere
  {% endif -%}